pipeline:
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: jt1000/go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: getpipeconfigfile
                  spec:
                    shell: Bash
                    command: <+input>
                  timeout: ""
                  type: Run
                  description: make pip file
              - step:
                  type: Run
                  name: get docker version
                  identifier: get_docker_version
                  spec:
                    shell: Bash
                    command: |-
                      docker -v;
                      cat pip.conf;
                      if [ -f pip.conf ]; then echo "pip.conf exists."; else echo "pip.conf does not exists."; fi
                      DOCKER_BUILDKIT=1 docker build --secret id=pip,src=pip.conf -f dockerfiles/preferences-api-dockerfile .
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths:
              - .gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        type: CI
        description: ""
    - stage:
        name: email_notification
        identifier: email_notification
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Email
                  name: Email_1
                  identifier: Email_1
                  spec:
                    to: jateen.bhatt@harness.io
                    cc: ""
                    subject: DPC_Direct3X_<+pipeline.stages.Clone.variables.Environment>_<+pipeline.stages.Clone.variables.Scope>_Automation
                    body: <+pipeline.stages.Clone.spec.execution.steps.CodeBuild.output.outputVariables.result>
                  timeout: 10m
        tags: {}
  identifier: secrettest
  tags: {}
  name: secret-test
