pipeline:
  identifier: Build_go_pipeline_sample_1688062987140
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: jt1000/go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get update
                      sudo apt-get install -y openjdk-17-jdk
                      sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
                      sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    shell: Sh
                    command: |
                      curl -I https://repo.maven.apache.org/maven2/com/rudderstack/android/sdk/core/1.21.0/core-1.21.0.pom
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths:
              - .gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        type: CI
        variables:
          - name: releaseTicket
            type: String
            description: ""
            required: false
            value: <+input>.regex(^CHG\d{8}$)
        description: ""
    - stage:
        name: email_notification
        identifier: email_notification
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Email
                  name: Email_1
                  identifier: Email_1
                  spec:
                    to: jateen.bhatt@harness.io
                    cc: ""
                    subject: DPC_Direct3X_<+pipeline.stages.Clone.variables.Environment>_<+pipeline.stages.Clone.variables.Scope>_Automation
                    body: <+pipeline.stages.Clone.spec.execution.steps.CodeBuild.output.outputVariables.result>
                  timeout: 10m
        tags: {}
    - stage:
        name: variableteststage
        identifier: variableteststage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "<+pipeline.properties.ci.codebase.build.spec.branch>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
