pipeline:
  identifier: Build_go_pipeline_sample_1688062987140
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: jt1000/go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    shell: Bash
                    command: |
                      echo Version parsed by regex is <+regex.extract("\d+(\.\d+)+|\d+", <+artifact.metadata.fileName>)>
                      curl -sS -X POST -H 'Content-Type: application/json' http://assist-npn-p-1.sys.ds.wolseley.com:8080/deployment/mark --data '{"service":"<+service.name>", "serverName":"<+instance.hostName>", "version":"<+regex.extract("\d+(\.\d+)+|\d+", <+artifact.metadata.fileName>)>", "update":"true"}' || true
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        variables:
          - name: releaseTicket
            type: String
            description: ""
            required: false
            value: <+input>.regex(^CHG\d{8}$)
    - stage:
        name: email_notification
        identifier: email_notification
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Email
                  name: Email_1
                  identifier: Email_1
                  spec:
                    to: jateen.bhatt@harness.io
                    cc: ""
                    subject: DPC_Direct3X_<+pipeline.stages.Clone.variables.Environment>_<+pipeline.stages.Clone.variables.Scope>_Automation
                    body: <+pipeline.stages.Clone.spec.execution.steps.CodeBuild.output.outputVariables.result>
                  timeout: 10m
        tags: {}
